#include <bits/stdc++.h>
using namespace std;
// Now creating a function for printing a array

// Now creating global varible for the time
double time_for_selection = 0;
void PrintElements(int array[], int size)
{
    cout << "\n\tPrinting a Elements \n";
    for (int i = 0; i < size; i++)
    {
        if (i % 10 == 0)
        {
            cout << endl;
        }
        printf("%5d",array[i]);
    }
    cout << endl;
}
// this is the function of the selection sort

void selectionSort(int arr[], int Size)
{
    clock_t start, end;
    start = clock();
    for (int i = 0; i < Size; i++)
        {
            for (int j = 0; j < Size; j++)
            {
                if (arr[j] < arr[i])
                {
                    swap(arr[j], arr[i]);
                }
            }
        }
    end = clock();
    time_for_selection = (double)((end - start) / CLOCKS_PER_SEC);
}
int main()
{
    /// Now here creating a Array First with random numbers generated by the random  number generator

    // Now asking a user how many numbers are you need to generating
    int size;
    cout << "How many numbers are you need to generating ? " << endl;
    cin >> size;

    // Now creating a array

    int Array[size];
    // Now initalize all with the rand() function
    for (int i = 0; i < size; i++)
    {
        Array[i] = rand() % 10000 + 1;
    }
    cout << "Before Sorting -->  ";
    PrintElements(Array, size);
    cout << "After Sorting --> \n";
    PrintElements(Array, size);
    printf("Time Taken by the selection sort is  %.3lf SECONDS", time_for_selection);
}